import tv from "../assets/imgs/img.png";
import imgN from "../assets/imgs/imgN.png";
// import imgN1 from "../assets/imgs/imgN1.png";
// import imgN2 from "../assets/imgs/furniture.png";
// import imgN3 from "../assets/imgs/img.png";

export const Electronics = [
  { id: 1,  name_uz: "All",  name_ru: "All", name_en: "All" },
  { id: 2,  name_uz: "Chair",  name_ru: "Chair", name_en: "Chair" },
  { id: 3,  name_uz: "HoReCa",  name_ru: "HoReCa", name_en: "HoReCa" },
  { id: 4,  name_uz: "Bedroom",  name_ru: "Bedroom", name_en: "Bedroom" },
  { id: 5,  name_uz: "Chair",  name_ru: "Chair", name_en: "Chair" },
  { id: 6,  name_uz: "Chair",  name_ru: "Chair", name_en: "Chair" },
  { id: 7,  name_uz: "Chair",  name_ru: "Chair", name_en: "Chair" },
  { id: 8,  name_uz: "Chair",  name_ru: "Chair", name_en: "Chair" },
  { id: 9,  name_uz: "RestRoom",  name_ru: "RestRoom", name_en: "RestRoom" },
];

export const ProdName = [
  { id: 1,  name_uz: "Phone",  name_ru: "Phone", name_en: "Refrigerator", category: 1},
  { id: 2,  name_uz: "Phone",  name_ru: "Phone", name_en: "TV", category: 1},
  { id: 3,  name_uz: "Phone",  name_ru: "Phone", name_en: "Phone", category: 1},
  { id: 4,  name_uz: "Phone",  name_ru: "Phone", name_en: "Washing machine", category: 1},
  { id: 5,  name_uz: "Phone",  name_ru: "Phone", name_en: "Washing machine", category: 1},
  { id: 6,  name_uz: "Phone",  name_ru: "Phone", name_en: "Blender", category: 1},
  { id: 7,  name_uz: "Phone",  name_ru: "Phone", name_en: "Refrigerator", category: 1},
  { id: 8,  name_uz: "Phone",  name_ru: "Phone", name_en: "Washing machine", category: 1},
];

export const CardData = [
  {
    id: 1,
    name_en: "Papel 040  HI tech",
    name_uz: "Papel 040  HI tech",
    name_ru: "Papel 040  HI tech",
    subname_en: "TV",
    price: 200,    
    sale: true,
    rate: 3,
    image: `${imgN}`,
    image1: `${imgN}`,
    image2: `${imgN}`,
    image3: `${imgN}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 2,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 2,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 3,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 4,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",    
  },
  {
    id: 4,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: true,
    rate: 4,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 5,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 5,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 6,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,    
    aksiya: 180,
    sale: true,
    rate: 1,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 7,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 4,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 8,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 3,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",    
  },
  {
    id: 9,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: true,
    rate: 3,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 10,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 2,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 11,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,    
    aksiya: 180,
    sale: true,
    rate: 2,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 12,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 4,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 1,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 13,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 4,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 2,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",    
  },
  {
    id: 14,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: true,
    rate: 5,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 2,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
  {
    id: 15,
    name_en: "Minimal LCD chair",
    name_uz: "Minimal LCD chair",
    name_ru: "Minimal LCD chair",
    subname_en: "TV",
    price: 200,
    aksiya: 180,
    sale: false,
    rate: 3,
    image: `${tv}`,
    image1: `${tv}`,
    image2: `${tv}`,
    image3: `${tv}`,
    persent: 25,
    category: 2,
    sub_category:1,
    description_en: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_uz: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
    description_ru: "sdj ksjdfkjsdkj sdjkj ksdjkfj sjdkjfkjspo] fg ]fkghpjk dfg h dt dgjf dsfh jvhfhgdfglk; dfjgk jdfjgk",
  },
];
